name: configdirector_flutter_sample_app
description: "Sample app for the ConfigDirector Flutter client SDK."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.4.0
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  configdirector_flutter_client_sdk: ^1.0.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ">=4.0.0 <7.0.0"

flutter:
  uses-material-design: true
