name: configdirector_openfeature_flutter_provider
description: "OpenFeature provider for ConfigDirector on Flutter. ConfigDirector is a remote configuration and feature flag service."
version: 0.1.0-beta.2
homepage: https://www.configdirector.com
repository: https://github.com/ConfigDirector/flutter-client-sdk/tree/main/packages/configdirector_openfeature_flutter_provider
issue_tracker: https://github.com/ConfigDirector/flutter-client-sdk/issues
documentation: https://docs.configdirector.com/sdks/openfeature/flutter

topics:
  - feature-flags
  - remote-config
  - openfeature

environment:
  sdk: ^3.12.2
  flutter: ">=3.44.2"

dependencies:
  flutter:
    sdk: flutter
  configdirector_flutter_client_sdk: ^1.3.0
  openfeature_dart_client_sdk: ^0.0.1-beta.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
